// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXscGYh99kegGCNxCi9lgyQnU2GqXnV3U',
    appId: '1:268944222200:web:0c2cf5361e15c9439b580d',
    messagingSenderId: '268944222200',
    projectId: 'movieappflutter-669d3',
    authDomain: 'movieappflutter-669d3.firebaseapp.com',
    storageBucket: 'movieappflutter-669d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcPguaP1vCAv-4UjJyWwtQVqeAwSHY83E',
    appId: '1:268944222200:android:5acf1a0cad3fd4969b580d',
    messagingSenderId: '268944222200',
    projectId: 'movieappflutter-669d3',
    storageBucket: 'movieappflutter-669d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmprcYOrV3pvNRbCe0AH_1bkjLUrqfzWI',
    appId: '1:268944222200:ios:e00b5a89fc6916749b580d',
    messagingSenderId: '268944222200',
    projectId: 'movieappflutter-669d3',
    storageBucket: 'movieappflutter-669d3.firebasestorage.app',
    iosBundleId: 'com.example.welcomeToFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmprcYOrV3pvNRbCe0AH_1bkjLUrqfzWI',
    appId: '1:268944222200:ios:e00b5a89fc6916749b580d',
    messagingSenderId: '268944222200',
    projectId: 'movieappflutter-669d3',
    storageBucket: 'movieappflutter-669d3.firebasestorage.app',
    iosBundleId: 'com.example.welcomeToFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXscGYh99kegGCNxCi9lgyQnU2GqXnV3U',
    appId: '1:268944222200:web:53e8b2b29d7b04bd9b580d',
    messagingSenderId: '268944222200',
    projectId: 'movieappflutter-669d3',
    authDomain: 'movieappflutter-669d3.firebaseapp.com',
    storageBucket: 'movieappflutter-669d3.firebasestorage.app',
  );
}
